! DESCRIP.MMS - build XZ Utils for OpenVMS (IA64, x86-64)
!
! Run from the top of the prepared source tree via [.VMS]BUILD.COM, which
! passes ARCH (IA64 or X86_64) and creates the output directories.  Source
! lists and per-object rules come from [.VMS]SOURCES.MMS and each program's
! objects from [.VMS]PROGS.MMS, both generated by tools/prepare.sh.
!
! Outputs:
!   [.OBJ_<arch>]LIBLZMA.OLB             the library (liblzma)
!   [.BIN_<arch>]XZ.EXE, XZDEC.EXE, LZMAINFO.EXE
!   [.INSTALL_<arch>.INCLUDE]LZMA.H, LZMA_*.H, [.INSTALL_<arch>.LIB]LIBLZMA.OLB

.IFDEF ARCH
.ELSE
ARCH = IA64
.ENDIF

OBJ = [.OBJ_$(ARCH)]
LOBJ = [.OBJ_$(ARCH).LIB]
BIN = [.BIN_$(ARCH)]
INST = [.INSTALL_$(ARCH)

.INCLUDE [.VMS]SOURCES.MMS
.INCLUDE [.VMS]PROGS.MMS

LIB = $(OBJ)LIBLZMA.OLB

CC = CC
! The programs: src/common and liblzma's public headers (src/xz/Makefile.am).
CFLAGS = $(CC_QUAL)/NOLIST/INCLUDE_DIRECTORY=("./lib","./src/common","./src/liblzma/api","./vms")-
	/DEFINE=($(CC_DEFS),HAVE_CONFIG_H)
! liblzma: its own include directories and tuklib's symbol prefix
! (src/liblzma/Makefile.am).
LIB_CFLAGS = $(CC_QUAL)/NOLIST/INCLUDE_DIRECTORY=("./lib","./src/liblzma/api",-
	"./src/liblzma/common","./src/liblzma/check","./src/liblzma/lz",-
	"./src/liblzma/rangecoder","./src/liblzma/lzma","./src/liblzma/delta",-
	"./src/liblzma/simple","./src/common")-
	/DEFINE=($(CC_DEFS),HAVE_CONFIG_H,"TUKLIB_SYMBOL_PREFIX=lzma_")

ALL : $(LIB), $(BIN)XZ.EXE, $(BIN)XZDEC.EXE, $(BIN)LZMAINFO.EXE, INSTALL_TREE
	@ CONTINUE

INSTALL_TREE : $(INST).LIB]LIBLZMA.OLB, $(INST).INCLUDE]LZMA.H
	@ CONTINUE

! "-": LINK and LIBRARY end with a warning status for modules compiled with
! VSI C's benign warnings; tools/build.sh fails the build on real errors.
$(BIN)XZ.EXE : $(XZ_OBJS), $(EXTRA_OBJS), $(LIB)
	- LINK/EXECUTABLE=$(MMS$TARGET)/MAP=$(OBJ)XZ.MAP/FULL $(XZ_OBJS), $(EXTRA_OBJS), $(LIB)/LIBRARY

$(BIN)XZDEC.EXE : $(XZDEC_OBJS), $(EXTRA_OBJS), $(LIB)
	- LINK/EXECUTABLE=$(MMS$TARGET)/MAP=$(OBJ)XZDEC.MAP/FULL $(XZDEC_OBJS), $(EXTRA_OBJS), $(LIB)/LIBRARY

$(BIN)LZMAINFO.EXE : $(LZMAINFO_OBJS), $(EXTRA_OBJS), $(LIB)
	- LINK/EXECUTABLE=$(MMS$TARGET)/MAP=$(OBJ)LZMAINFO.MAP/FULL $(LZMAINFO_OBJS), $(EXTRA_OBJS), $(LIB)/LIBRARY

$(LIB) : $(LIB_OBJS)
	IF F$SEARCH("$(MMS$TARGET)") .EQS. "" THEN LIBRARY/CREATE/OBJECT $(MMS$TARGET)
	- LIBRARY/REPLACE/OBJECT $(MMS$TARGET) $(LOBJ)*.OBJ

$(INST).LIB]LIBLZMA.OLB : $(LIB)
	COPY $(MMS$SOURCE) $(MMS$TARGET)

! lzma.h includes lzma_*.h on VMS (patch 0004; prepare.sh makes them).
$(INST).INCLUDE]LZMA.H : [.SRC.LIBLZMA.API]lzma.h
	COPY $(MMS$SOURCE) $(MMS$TARGET)
	COPY [.SRC.LIBLZMA.API]lzma_*.h $(INST).INCLUDE]

CLEAN :
	IF F$SEARCH("$(LOBJ)*.*") .NES. "" THEN DELETE/NOLOG $(LOBJ)*.*;*
	IF F$SEARCH("$(OBJ)*.OBJ") .NES. "" THEN DELETE/NOLOG $(OBJ)*.OBJ;*,*.OLB;*,*.MAP;*
	IF F$SEARCH("$(BIN)*.*") .NES. "" THEN DELETE/NOLOG $(BIN)*.*;*
