#!/usr/bin/env python3
"""Emit gl_cv_next_<header> answers mapping gnulib wrappers to CRTL text-library modules.

Usage: nextheaders_site.py <configure> <crtl_modules.txt> > next-headers.site

VSI C has no #include_next and its preprocessor output carries no file
names, so configure cannot find the "next" system header itself.  gnulib's
wrapper headers instead use '#include MODULE', which VSI C resolves from
SYS$LIBRARY:DECC$RTLDEF.TLB; MODULE is the header's basename.  Headers the
CRTL lacks get no entry (gnulib then does not include a system header).
"""
import re
import sys

configure = open(sys.argv[1], encoding='latin-1').read()
modules = {l.strip() for l in open(sys.argv[2]) if l.strip() and not l.startswith('#')}
print('# Generated by tools/nextheaders_site.py - do not edit.')
print('gl_cv_have_include_next=no')
for var in sorted(set(re.findall(r'\bgl_cv_next_([a-z0-9_]+)_h\b', configure))):
    module = var.split('_')[-1].upper()
    if module in modules:
        print('gl_cv_next_%s_h=%s' % (var, module))
